variable ENV {}

variable SIGNUP_ROLE_NAME {}
variable CONFIRM_SIGNUP_ROLE_NAME {}
variable RESEND_CONFIRMATION_CODE_ROLE_NAME {}
variable SIGNIN_ROLE_NAME {}
variable FORGOT_PASSWORD_ROLE_NAME {}
variable CONFIRM_FORGOT_PASSWORD_ROLE_NAME {}

variable CHANGE_PASSWORD_ROLE_NAME {}
variable DELETE_USER_ROLE_NAME {}
variable VIEW_PROFILE_ROLE_NAME {}
variable UPDATE_PROFILE_ROLE_NAME {}

variable AUTHORIZER_ROLE_NAME {}